apiVersion: apps/v1
kind: Deployment
metadata:
    name: deploy-ngx
    namespace: devpods
    labels:
        app-deploy: ngx-deploy-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app-deploy: ngx-deploy-app
    template:
        metadata:
            labels:
                app-deploy: ngx-deploy-app
        spec:
            containers:
                - name: deploy-ngx
                  image: nginx:latest
                  ports:
                      - containerPort: 80
                  volumeMounts:
                      - name: nginx-html
                        mountPath: "/usr/share/nginx/html/"
            volumes:
                - name: nginx-html
                  hostPath:
                      path: "/home/emanuel/container/web"

---
apiVersion: v1
kind: Service
metadata:
    name: svc-loadbalancer
    namespace: devpods
spec:
    type: LoadBalancer
    selector:
        app-deploy: ngx-deploy-app
    ports:
        - name: http
          port: 4000
          targetPort: 80
    externalIPs:
    - 10.0.1.106
