apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app-nginx
  namespace: devpods
  labels:
    app-deploy: deploy-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app-deploy: deploy-nginx
  template:
    metadata:
      labels:
        app-deploy: deploy-nginx
    spec:
      containers:
        - name: deploy-app-nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html
              mountPath: "/usr/share/nginx/html/"
    volumes:
      - name: nginx-html
        hostPath:
          path: "/home/emanuel/container/web"

---
apiVersion: v1
kind: Service
metadata:
  name: svc-deploy-nginx
  namespace: devpods
  labels:
    app-deploy: deploy-nginx
spec:
  type: NodePort
  selector:
    app-deploy: deploy-nginx
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080 # mude para uma porta livre dentro do intervalo <30000-32767>
  externalIPs:
    -  # mude para o IP do cluster
