apiVersion: apps/v1
kind: Deployment
metadata:
    name: deploy-nginx
    namespace: devpods
    labels:
        app-deploy: nginx-deploy-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app-deploy: nginx-deploy-app
    template:
        metadata:
            labels:
                app-deploy: nginx-deploy-app
        spec:
            containers:
                - name: deploy-nginx
                  image: nginx:latest
                  ports:
                      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
    name: svc-loadbalancer
    namespace: devpods
spec:
    type: LoadBalancer
    selector:
        app-deploy: nginx-deploy-app
    ports:
        - name: http
          port: 4000
          targetPort: 80
    externalIPs:
        - 10.0.1.106
