apiVersion: apps/v1
kind: Deployment
metadata:
    name: deploy-ngx
    namespace: devpods
    labels:
        app-deploy: ngx-deploy-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app-deploy: ngx-deploy-app
    template:
        metadata:
            labels:
                app-deploy: ngx-deploy-app
        spec:
            containers:
                - name: deploy-ngx
                  image: nginx:latest
                  resources:
                      limits:
                          cpu: 700m # 70% of a single CPU core
                      requests:
                          cpu: 500m # 50% of a single CPU core
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: svc-loadbalancer
    namespace: devpods
spec:
    type: LoadBalancer
    selector:
        app-deploy: ngx-deploy-app
    ports:
        - name: http
          port: 4000
          targetPort: 80
    externalIPs:
        - 192.168.1.6
