apiVersion: v1
kind: Namespace
metadata:
    name: devpods
---
apiVersion: v1
kind: Pod
metadata:
    name: pod-ngx
    namespace: devpods
    labels:
        app.kubernetes.io/app: ngx-app
spec:
    containers:
        - name: pod-ngx
          image: nginx:latest
          ports:
              - name: http
                containerPort: 80
                hostPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: svc-ngx
    namespace: devpods
spec:
    selector:
        app.kubernetes.io/name: ngx-app
    type: NodePort
    ports:
        - protocol: TCP
          port: 80
          nodePort: 30080

