apiVersion: v1
kind: Namespace
metadata:
    name: devpods
---
apiVersion: v1
kind: Pod
metadata:
    name: pod-nginx
    namespace: devpods
    labels:
        app.kubernetes.io/app: nginx-app
spec:
    containers:
        - name: pod-nginx
          image: nginx:latest
          ports:
              - name: http
                containerPort: 80
                hostPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: svc-nginx
    namespace: devpods
spec:
    selector:
        app.kubernetes.io/name: nginx-app
    type: NodePort
    ports:
        - protocol: TCP
          port: 80
          nodePort: 30080

