apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
    app: monitoring-pod
  ports:
    name: prometheus
    protocol: TCP
    nodePort: 30098
    port: 80
    targetPort: 3000