apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: monitoring-pod
  ports:
    name: grafana
    protocol: TCP
    nodePort: 30090
    port: 9090
    targetPort: 9090

