apiVersion: v1
kind: Service
metadata:
  name: web-service-pod-one
spec:
  selector:
    app: first-web-pod
  ports:
    name: second-pod-web
    protocol: TCP
    nodePort: 30098
    port: 80
    targetPort: 3000