global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: "nginx"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8080"]
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9100"]
