apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev
  labels:
    app: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels: 
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        args: []
        VolumesMounts:
        - name: nginx-volume
          mountPath:
        ports:
        - containerPort: 80
      volumes: 
      - name: nginx-volume
        mountPath: 

---         

apiVersion: v1
kind: Service
metadata:
  name: service-nginx-deploy
  namespace: dev
spec:
  spec:
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80