apiVersion: v1
kind: Pod
metadata:
  name: monitoring-pod
spec:
  containers:
  - name: prometheus
    image: prom/prometheus
    ports:
    - containerPort: 9090
    volumeMounts:
    - name: prometheus-volume
      mountPath: /etc/prometheus
  - name: grafana
    image: grafana/grafana
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: grafana-volume
      mountPath: /var/lib/grafana
  volumes:
  - name: prometheus-volume
    hostPath:
      path: /home/$(whoami)/container/prometheus/
  - name: grafana-volume
    hostPath:
      path: /home/$(whoami)/container/grafana/
