apiVersion: v1
kind: Pod
metadata:
  name: web-pod-1
spec:
  containers:
  - name: web-container-1
    image: alpine
    command: ["apk add nginx"]
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html/
      name: html-volume
  volumes:
  - name: html-volume
    hostPath:
      path: /home/$(whoami)/container/web

